name: Docker Build & Push

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag lvkdotsh/dynamic-server

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          name: lvkdotsh/dynamic-server
