name: Docker Build & Push

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag lvkdotsh/dynamic-server

      - name: Publish to Registry
        run: |
            IMAGE_ID=lvkdotsh/dynamic-server

            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

            [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

            docker tag lvkdotsh/dynamic-server $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:latest
